server:
  port: 9834
spring:
  data.mongodb.uri:
    mongodb://host.docker.internal:27017/oauth_xyz

spring.data.rest.base-path: /api

oauth.xyz.root: http://host.docker.internal:9834/

rewrite:
  entries:
    - sourceUrl: /as/interact
      target: /
    - sourceUrl: /as
      target: /
    - sourceUrl: /c
      target: /

# spring.devtools.restart.exclude: 

spring.jackson.default-property-inclusion: non_null